//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdminLogin
{
    public long Id { get; set; }
    public string usertype { get; set; }
    public string LoginId { get; set; }
    public string Password { get; set; }
    public Nullable<System.DateTime> LastLogin { get; set; }
    public string username { get; set; }
    public bool Status { get; set; }
}

public partial class Banner
{
    public int BannerId { get; set; }
    public string BannerImg { get; set; }
    public string BannerUrl { get; set; }
    public string BannerTitle { get; set; }
    public Nullable<int> DisplayOrder { get; set; }
    public System.DateTime CreateDate { get; set; }
    public string BannerOf { get; set; }
}

public partial class Catalog
{
    public int Id { get; set; }
    public string Img { get; set; }
    public string Title { get; set; }
    public string Pdf { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
}

public partial class CategoryMaster
{
    public decimal CategoryId { get; set; }
    public string CategoryName { get; set; }
    public string CategoryImg { get; set; }
    public int DisplayOrder { get; set; }
    public string Icon { get; set; }
}

public partial class CollectionBanner
{
    public decimal Id { get; set; }
    public string Position { get; set; }
    public string Title { get; set; }
    public string ImgName { get; set; }
    public string Url { get; set; }
    public Nullable<System.DateTime> AdDate { get; set; }
}

public partial class CollectionMaster
{
    public decimal CollectionId { get; set; }
    public string CollectionName { get; set; }
    public string CollectionImg { get; set; }
    public int DisplayOrder { get; set; }
    public string CollectionIcon { get; set; }
}

public partial class ColorMaster
{
    public decimal ColorId { get; set; }
    public string ColorName { get; set; }
    public Nullable<int> Status { get; set; }
    public Nullable<System.DateTime> AdDate { get; set; }
}

public partial class ContactU
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string ContactNo { get; set; }
    public string Subject { get; set; }
    public string Message { get; set; }
    public Nullable<System.DateTime> AdDate { get; set; }
}

public partial class DiscountCoupon
{
    public int Id { get; set; }
    public decimal DiscountPerc { get; set; }
    public string DiscountCode { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> Addon { get; set; }
    public Nullable<System.DateTime> EditedOn { get; set; }
}

public partial class Exibition
{
    public int ExibitionId { get; set; }
    public string ExibitionName { get; set; }
    public System.DateTime Exibitiondate { get; set; }
    public string ExibitionPlace { get; set; }
    public string ContactNo { get; set; }
    public string HallNo { get; set; }
    public string BoothNo { get; set; }
    public string MianImage { get; set; }
    public string OtherImage { get; set; }
    public string Description { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<System.DateTime> ToDate { get; set; }
    public Nullable<System.DateTime> AddedDate { get; set; }
}

public partial class FeatureMaster
{
    public int FeatureId { get; set; }
    public string FeatureName { get; set; }
    public int FeatureGroupId { get; set; }
    public int DisplayOrder { get; set; }
    public System.DateTime CreateDate { get; set; }
}

public partial class HomeGalleryBanner
{
    public decimal BannerId { get; set; }
    public string BannerImg { get; set; }
    public string BannerUrl { get; set; }
    public string BannerTitle { get; set; }
    public Nullable<int> DisplayOrder { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class Itembanner
{
    public int Id { get; set; }
    public string Item { get; set; }
    public string Imagename { get; set; }
    public string ImageUrl { get; set; }
    public Nullable<System.DateTime> Adddate { get; set; }
}

public partial class LoginHistory
{
    public decimal Id { get; set; }
    public string UserName { get; set; }
    public Nullable<System.DateTime> LoginDate { get; set; }
    public Nullable<System.DateTime> LogoutDate { get; set; }
    public string Staytime { get; set; }
    public string from { get; set; }
    public string Email { get; set; }
    public string ContactNo { get; set; }
    public string PlayerId { get; set; }
    public string DeviceId { get; set; }
    public string DeviceName { get; set; }
    public string Location { get; set; }
}

public partial class MaterialMaster
{
    public decimal MaterialId { get; set; }
    public string Material { get; set; }
    public string Status { get; set; }
}

public partial class NewsLetter
{
    public int Id { get; set; }
    public string EmailId { get; set; }
    public Nullable<int> Status { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class OrderBillingInfo
{
    public long Id { get; set; }
    public string OrderNo { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Address2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string Zip { get; set; }
    public string ContactNo { get; set; }
    public string Email { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class OrderDetail
{
    public long Id { get; set; }
    public string OrderNo { get; set; }
    public Nullable<long> ProductId { get; set; }
    public string ModelNo { get; set; }
    public string Item { get; set; }
    public string Img { get; set; }
    public string Size { get; set; }
    public Nullable<int> Qty { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<decimal> Total { get; set; }
    public string Comment { get; set; }
    public string ShortDesc { get; set; }
    public Nullable<decimal> discountedprice { get; set; }
}

public partial class OrderPaymentResponse
{
    public long Id { get; set; }
    public string OrderId { get; set; }
    public string PaymentId { get; set; }
    public string Mode { get; set; }
    public string Status { get; set; }
    public string Message { get; set; }
    public System.DateTime CreateDate { get; set; }
    public string PaymentMode { get; set; }
}

public partial class OrderShippingDetail
{
    public long Id { get; set; }
    public string OrderNo { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Address2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string Zip { get; set; }
    public string ContactNo { get; set; }
    public string Email { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class OrderTbl
{
    public long Id { get; set; }
    public string OrderNo { get; set; }
    public long UserId { get; set; }
    public decimal OrderTotal { get; set; }
    public string OrderCurrency { get; set; }
    public Nullable<decimal> ShippingAmt { get; set; }
    public string CouponCode { get; set; }
    public string CouponType { get; set; }
    public Nullable<decimal> CouponAmt { get; set; }
    public string Comment { get; set; }
    public string status { get; set; }
    public string OrderBy { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
}

public partial class OrderTracking
{
    public long Id { get; set; }
    public string OrderNo { get; set; }
    public string OrderStatus { get; set; }
    public Nullable<System.DateTime> StatusDate { get; set; }
    public string ShippedBy { get; set; }
    public string TarckNo { get; set; }
    public string Comments { get; set; }
    public Nullable<System.DateTime> ShippedDate { get; set; }
    public Nullable<System.DateTime> ExpectedDeliverDate { get; set; }
    public Nullable<System.DateTime> DeliveredDate { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class OtherImage
{
    public decimal Id { get; set; }
    public Nullable<decimal> ProductId { get; set; }
    public string ImageName { get; set; }
    public Nullable<int> Displayorder { get; set; }
}

public partial class ProductFeature
{
    public long ProductFeatureId { get; set; }
    public long ProductId { get; set; }
    public long FeatureId { get; set; }
    public string FeatureValue { get; set; }
}

public partial class Producthistory
{
    public decimal Id { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<decimal> ProductId { get; set; }
    public string from { get; set; }
    public Nullable<System.DateTime> viewdate { get; set; }
}

public partial class ProductMaster
{
    public decimal Id { get; set; }
    public string SkuName { get; set; }
    public Nullable<decimal> CollectionId { get; set; }
    public Nullable<decimal> CategoryId { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> MaterialId { get; set; }
    public Nullable<decimal> SizeId { get; set; }
    public string AvlSizes { get; set; }
    public Nullable<decimal> ColorId { get; set; }
    public string AvlColors { get; set; }
    public string Variations { get; set; }
    public string GenderType { get; set; }
    public Nullable<decimal> MRP { get; set; }
    public Nullable<decimal> SRP { get; set; }
    public Nullable<decimal> Offerprice { get; set; }
    public Nullable<decimal> StockPcs { get; set; }
    public Nullable<decimal> Grosswt { get; set; }
    public Nullable<decimal> NetWt { get; set; }
    public Nullable<int> ShowHide { get; set; }
    public Nullable<System.DateTime> MDate { get; set; }
    public Nullable<int> IsCommon { get; set; }
    public string Image { get; set; }
    public string OtherImage { get; set; }
}

public partial class ProductMaster_1
{
    public decimal Id { get; set; }
    public Nullable<decimal> SkuId { get; set; }
    public Nullable<decimal> ReadyId { get; set; }
    public string SkuName { get; set; }
    public string ItemName { get; set; }
    public string StyleName { get; set; }
    public string SgroupName { get; set; }
    public string MetalName { get; set; }
    public string SizeName { get; set; }
    public string ItemLength { get; set; }
    public string colorName { get; set; }
    public Nullable<double> Grosswt { get; set; }
    public string Designno { get; set; }
    public Nullable<decimal> StockPcs { get; set; }
    public Nullable<double> Price { get; set; }
    public double Offerprice { get; set; }
    public string Remark { get; set; }
    public decimal TotalDiaWt { get; set; }
    public decimal TotalDiaPcs { get; set; }
    public decimal TotalCsWt { get; set; }
    public decimal TotalCsPcs { get; set; }
    public int ShowHide { get; set; }
    public Nullable<System.DateTime> MDate { get; set; }
    public Nullable<int> IsCommon { get; set; }
}

public partial class ProductReview
{
    public decimal Id { get; set; }
    public Nullable<decimal> ProductId { get; set; }
    public string ItemCode { get; set; }
    public string Name { get; set; }
    public string Review { get; set; }
    public Nullable<int> Rating { get; set; }
    public Nullable<System.DateTime> AdDate { get; set; }
    public Nullable<int> Status { get; set; }
}

public partial class productstone
{
    public decimal Id { get; set; }
    public Nullable<decimal> Readyid { get; set; }
    public string StoneName { get; set; }
    public string ShapeName { get; set; }
    public string StoneTypeName { get; set; }
    public string QualityName { get; set; }
    public string SizeName { get; set; }
    public decimal StoneWeight { get; set; }
    public decimal StonePcs { get; set; }
}

public partial class Seo
{
    public int Id { get; set; }
    public string Url { get; set; }
    public string Title { get; set; }
    public string keyword { get; set; }
    public string Description { get; set; }
    public string MetaUrl { get; set; }
    public string barcode { get; set; }
    public Nullable<decimal> ProId { get; set; }
}

public partial class ShipMaster
{
    public long Id { get; set; }
    public string ShipName { get; set; }
    public string ShipWebsite { get; set; }
    public string TrackUrl { get; set; }
    public string ContactNo { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class SizeMaster
{
    public decimal SizeId { get; set; }
    public string SizeName { get; set; }
    public Nullable<int> Status { get; set; }
    public Nullable<System.DateTime> AdDate { get; set; }
}

public partial class StripBanner
{
    public int BannerId { get; set; }
    public string BannerImg { get; set; }
    public string BannerUrl { get; set; }
    public string BannerTitle { get; set; }
    public Nullable<int> DisplayOrder { get; set; }
    public System.DateTime CreateDate { get; set; }
    public string BannerOf { get; set; }
    public string BannerImgMobile { get; set; }
}

public partial class UserInfo
{
    public long Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Company { get; set; }
    public string ContactPerson { get; set; }
    public string Designation { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string Zip { get; set; }
    public string ContactNo { get; set; }
    public string Gender { get; set; }
    public string Email { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public bool IsActive { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string Registerfrom { get; set; }
    public string Productids { get; set; }
    public Nullable<int> Mailstatus { get; set; }
    public string DeviceId { get; set; }
    public string PlayerId { get; set; }
}

public partial class USPDetail
{
    public int UspId { get; set; }
    public string UspTitle { get; set; }
    public string UspSubTitle { get; set; }
    public string Url { get; set; }
    public string IconImageName { get; set; }
    public Nullable<int> DisplayOrder { get; set; }
}

public partial class WebCollInnerBanner
{
    public int BannerId { get; set; }
    public string CollectionName { get; set; }
    public string BannerImg { get; set; }
    public string BannerUrl { get; set; }
    public string BannerTitle { get; set; }
    public string Heading { get; set; }
    public string Subheading { get; set; }
    public System.DateTime CreateDate { get; set; }
}
